Torture test isn't throwing NPEs anymore
getASTNode() is sometimes imperfect - it doesn't return the actual node.
However, I've found a way to resolve this by going up the tree until we
find a Block and then running the search.

However, we are running out of heap space because of all the compilation
units in memory:

java.lang.OutOfMemoryError: Java heap space
at
org.eclipse.jdt.internal.compiler.parser.Parser.newMessageSend(Parser.java:9517)
at
org.eclipse.jdt.internal.compiler.parser.Parser.consumeMethodInvocationName(Parser.java:4802)
at
org.eclipse.jdt.internal.compiler.SourceElementParser.consumeMethodInvocationName(SourceElementParser.java:439)
at
org.eclipse.jdt.internal.compiler.parser.Parser.consumeRule(Parser.java:6177)
at
org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:9694)
at
org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:10034)
at
org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.parseStatements(MethodDeclaration.java:161)
at
org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.parseMethods(TypeDeclaration.java:869)
at
org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.parseMethods(TypeDeclaration.java:859)
at
org.eclipse.jdt.internal.compiler.parser.Parser.getMethodBodies(Parser.java:8872)
at
org.eclipse.jdt.internal.compiler.SourceElementParser.parseCompilationUnit(SourceElementParser.java:931)
at
org.eclipse.jdt.internal.core.CompilationUnit.buildStructure(CompilationUnit.java:198)
at
org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:258)
at
org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:521)
at
org.eclipse.jdt.internal.core.BecomeWorkingCopyOperation.executeOperation(BecomeWorkingCopyOperation.java:38)
at
org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:728)
at
org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:788)
at
org.eclipse.jdt.internal.core.CompilationUnit.becomeWorkingCopy(CompilationUnit.java:100)
at
org.eclipse.jdt.internal.core.CompilationUnit.becomeWorkingCopy(CompilationUnit.java:108)
at
edu.umd.cs.findbugs.plugin.eclipse.quickfix.BugResolution.createWorkingCopy(BugResolution.java:334)
at
edu.umd.cs.findbugs.plugin.eclipse.quickfix.BugResolution.makeOrReuseWorkingCopy(BugResolution.java:216)
at
edu.umd.cs.findbugs.plugin.eclipse.quickfix.BugResolution.resolveWithoutWriting(BugResolution.java:190)
at
edu.umd.cs.findbugs.plugin.eclipse.quickfix.BugResolution.run(BugResolution.java:151)
at
org.eclipse.ui.internal.views.markers.QuickFixPage$11.run(QuickFixPage.java:565)
at
org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:464)
at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:372)
at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1028)
at
org.eclipse.ui.internal.views.markers.QuickFixPage.performFinish(QuickFixPage.java:554)
at
org.eclipse.ui.internal.views.markers.QuickFixWizard$1.run(QuickFixWizard.java:97)
at
org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:464)
at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:372)
at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1028)